[Definition]
actionstart = /etc/fail2ban/action.d/mqtt.sh --action=start
actionstop = /etc/fail2ban/action.d/mqtt.sh --action=stop
actioncheck =
actionban = /etc/fail2ban/action.d/mqtt.sh --action=ban --service=<name> --ip=<ip>
actionunban = /etc/fail2ban/action.d/mqtt.sh --action=unban --service=<name> --ip=<ip>

[Init]
init = 123