- name: "deploy ARK: Survival Evolved Dedicated Server"
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  vars:
    stack: "ark-survival-evolved"
    image: "ich777/steamcmd:arkse"
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose' directory"
    file:
      path: "{{base_dir}}/compose"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose/{{stack}}' directory"
    file:
      path: "{{base_dir}}/compose/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/docker/{{stack}}' directory"
    become: true
    become_method: sudo
    file:
      path: "{{base_dir}}/docker/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "writing '{{base_dir}}/compose/{{stack}}/compose.yml'"
    become: true
    become_method: sudo
    copy:
      dest: "{{base_dir}}/compose/{{stack}}/compose.yml"
      owner: "{{ssh_user}}"
      content: |
        services:
          ark-survival-evolved:
            restart: unless-stopped
            container_name: ark-survival-evolved
            image: ich777/steamcmd:arkse
            ports:
              - "{{ ark_survival_evolved_port | default('7777') }}:7777/udp"
              - "7778:7778/udp"
              - "{{ ark_survival_evolved_query_port | default('27015') }}:27015/udp"
              - "{{ ark_survival_evolved_rcon_port | default('27020') }}:27020/tcp"
            environment:
              - GAME_ID=376030
              - MAP=TheIsland
              - SERVER_NAME={{ ark_survival_evolved_server_name | default('AnsimateARKServer') }}
              - SRV_PWD={{ ark_survival_evolved_password | default('changeme') }}
              - SRV_ADMIN_PWD={{ ark_survival_evolved_rcon_password | default('AdminPleaseChangeMe') }}
              - GAME_PARAMS=?MaxPlayers=20
              - GAME_PARAMS_EXTRA=-server -log
              - VALIDATE=true
              - UID=99
              - GID=100
            volumes:
              - "{{base_dir}}/docker/{{stack}}:/serverdata/serverfiles"
#---------------------------------------------------------------------------------------------
  - name: "start compose stack"
    become: true
    become_method: sudo
    command: "docker compose up -d"
    args:
      chdir: "{{base_dir}}/compose/{{stack}}"
