- name: deploy DayZ Dedicated Server
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  vars:
    stack: "dayz"
    image: "ich777/steamcmd:dayz"
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose' directory"
    file:
      path: "{{base_dir}}/compose"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose/{{stack}}' directory"
    file:
      path: "{{base_dir}}/compose/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/docker/{{stack}}' directory"
    become: true
    become_method: sudo
    file:
      path: "{{base_dir}}/docker/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "writing '{{base_dir}}/compose/{{stack}}/compose.yml'"
    become: true
    become_method: sudo
    copy:
      dest: "{{base_dir}}/compose/{{stack}}/compose.yml"
      owner: "{{ssh_user}}"
      content: |
        services:
          dayz:
            restart: unless-stopped
            container_name: dayz
            image: ich777/steamcmd:dayz
            ports:
              - "2302:2302/udp"
              - "2303:2303/udp"
              - "2304:2304/udp"
              - "27016:27016/udp"
            environment:
              - GAME_ID=1042420
              - GAME_PORT=2302
              - GAME_PARAMS=
              - VALIDATE=true
              - USERNAME=
              - PASSWRD=
              - UID=99
              - GID=100
            volumes:
              - "{{base_dir}}/docker/{{stack}}:/serverdata/serverfiles"
#---------------------------------------------------------------------------------------------
  - name: "start compose stack"
    become: true
    become_method: sudo
    command: "docker compose up -d"
    args:
      chdir: "{{base_dir}}/compose/{{stack}}"
