- name: deploy Astroneer Dedicated Server
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  vars:
    stack: "astroneer"
    image: "barumel/docker-astroneer-server:latest"
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose' directory"
    file:
      path: "{{base_dir}}/compose"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose/{{stack}}' directory"
    file:
      path: "{{base_dir}}/compose/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/docker/{{stack}}' directory"
    become: true
    become_method: sudo
    file:
      path: "{{base_dir}}/docker/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "writing '{{base_dir}}/compose/{{stack}}/compose.yml'"
    become: true
    become_method: sudo
    copy:
      dest: "{{base_dir}}/compose/{{stack}}/compose.yml"
      owner: "{{ssh_user}}"
      content: |
        services:
          astroneer:
            restart: unless-stopped
            container_name: astroneer
            image: barumel/docker-astroneer-server:latest
            ports:
              - "{{ astroneer_port | default('8777') }}:8777/udp"
              - "{{ astroneer_port | default('8777') }}:8777/tcp"
            environment:
              - ASTRO_SERVER_NAME={{ astroneer_server_name | default('Astroneer Dedicated Server') }}
              - ASTRO_SERVER_OWNER_NAME=SteamOwnerName
              - ASTRO_SERVER_PASSWORD={{ astroneer_password | default('changeme') }}
              - ASTRO_SERVER_PORT={{ astroneer_port | default('8777') }}
              - ASTRO_SERVER_AUTO_SAVE_INTERVAL=60
              - ASTRO_SERVER_DISABLE_ENCRYPTION=false
            volumes:
              - "{{base_dir}}/docker/{{stack}}:/astroneer"
#---------------------------------------------------------------------------------------------
  - name: "start compose stack"
    become: true
    become_method: sudo
    command: "docker compose up -d"
    args:
      chdir: "{{base_dir}}/compose/{{stack}}"
