- name: deploy Soulmask Dedicated Server
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  vars:
    stack: "soulmask"
    image: "sknnr/soulmask-dedicated-server:latest"
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose' directory"
    file:
      path: "{{base_dir}}/compose"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose/{{stack}}' directory"
    file:
      path: "{{base_dir}}/compose/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/docker/{{stack}}' directory"
    become: true
    become_method: sudo
    file:
      path: "{{base_dir}}/docker/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "writing '{{base_dir}}/compose/{{stack}}/compose.yml'"
    become: true
    become_method: sudo
    copy:
      dest: "{{base_dir}}/compose/{{stack}}/compose.yml"
      owner: "{{ssh_user}}"
      content: |
        services:
          soulmask:
            restart: unless-stopped
            container_name: soulmask
            image: sknnr/soulmask-dedicated-server:latest
            ports:
              - "{{ soulmask_port | default('27050') }}:27050/udp"
              - "{{ soulmask_query_port | default('27051') }}:27051/udp"
              - "{{ soulmask_rcon_port | default('19000') }}:19000/tcp"
            environment:
              - SERVER_NAME={{ soulmask_server_name | default('Soulmask Server') }}
              - GAME_MODE=pve
              - SERVER_SLOTS={{ soulmask_max_players | default('50') }}
              - SERVER_LEVEL=Level01_Main
              - ADMIN_PASSWORD=AdminPleaseChangeMe
              - SERVER_PASSWORD={{ soulmask_password | default('') }}
              - GAME_PORT={{ soulmask_port | default('27050') }}
              - QUERY_PORT={{ soulmask_query_port | default('27051') }}
              - RCON_PORT={{ soulmask_rcon_port | default('19000') }}
              - RCON_PASSWORD={{ soulmask_rcon_password | default('') }}
              - BACKUP=900
              - SAVING=600
            volumes:
              - "{{base_dir}}/docker/{{stack}}:/home/steam/soulmask"
#---------------------------------------------------------------------------------------------
  - name: "start compose stack"
    become: true
    become_method: sudo
    command: "docker compose up -d"
    args:
      chdir: "{{base_dir}}/compose/{{stack}}"
