- name: deploy Don't Starve Together Dedicated Server
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  vars:
    stack: "dont-starve-together"
    image: "jamesits/dst-server:latest"
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose' directory"
    file:
      path: "{{base_dir}}/compose"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose/{{stack}}' directory"
    file:
      path: "{{base_dir}}/compose/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/docker/{{stack}}' directory"
    become: true
    become_method: sudo
    file:
      path: "{{base_dir}}/docker/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "writing '{{base_dir}}/compose/{{stack}}/compose.yml'"
    become: true
    become_method: sudo
    copy:
      dest: "{{base_dir}}/compose/{{stack}}/compose.yml"
      owner: "{{ssh_user}}"
      content: |
        services:
          dont-starve-together:
            restart: unless-stopped
            container_name: dont-starve-together
            image: jamesits/dst-server:latest
            ports:
              - "10999:10999/udp"
              - "11000:11000/udp"
              - "12346:12346/udp"
              - "12347:12347/udp"
            environment:
              - DST_SERVER_ARCH=amd64
              - DST_CLUSTER_TOKEN=
            volumes:
              - "{{base_dir}}/docker/{{stack}}:/data"
#---------------------------------------------------------------------------------------------
  - name: "start compose stack"
    become: true
    become_method: sudo
    command: "docker compose up -d"
    args:
      chdir: "{{base_dir}}/compose/{{stack}}"
