- name: create compose for nodered
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  vars:
    stack: "nodered"
    image: "nodered/node-red:latest"
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose' directory"
    file:
      path: "{{base_dir}}/compose"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose/{{stack}}' directory"
    file:
      path: "{{base_dir}}/compose/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/docker' directory"
    become: true
    become_method: sudo
    file:
      path: "{{base_dir}}/docker"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/docker/{{stack}}' directory"
    become: true
    become_method: sudo
    file:
      path: "{{base_dir}}/docker/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: checking if '{{base_dir}}/compose/{{stack}}/compose.yml' is present
    stat:
      path: "{{base_dir}}/compose/{{stack}}/compose.yml"
    register: is_compose_present
#---------------------------------------------------------------------------------------------
  - name: make backup '{{base_dir}}/compose/{{stack}}/compose.yml' -> '{{base_dir}}/compose/{{stack}}/compose.yml.bak'
    command: "mv compose.yml compose.yml.bak"
    args:
      chdir: "{{base_dir}}/compose/{{stack}}"
    when: is_compose_present.stat.exists
#---------------------------------------------------------------------------------------------
  - name: creating '{{base_dir}}/compose/{{stack}}/compose.yml'
    command: "touch {{base_dir}}/compose/{{stack}}/compose.yml"
#---------------------------------------------------------------------------------------------
  - name: add component to compose.yml
    blockinfile: 
      state: present
      insertafter: EOF
      dest: "{{base_dir}}/compose/{{stack}}/compose.yml"
      marker: "#<!-- {{stack}} -->"
      content: |
        {% if use_traefik | default(false) | bool %}
        networks:
          local:
            external: true
        {% endif %}
        services:
          {{stack}}:
            restart: unless-stopped
            container_name: {{stack}}
            image: {{image}}
            hostname: "nodered.local"
            environment:
              - TZ={{timezone}}
            volumes:
              - {{base_dir}}/docker/{{stack}}:/data
        {% if use_traefik | default(false) | bool %}
            networks:
              - local
            labels:
              - homepage.group=Main
              - homepage.name=nodeRED
              - homepage.icon=node-red.png
              - homepage.href=http://{{nodered_domain}}
              - homepage.description=The automation platform
              - "traefik.http.routers.nodered_http.rule=Host(`{{nodered_domain}}`)"
              - traefik.http.routers.nodered_http.entrypoints=web
              - "traefik.http.routers.nodered_http.middlewares=bauth"
        {% else %}
            ports:
              - "{{nodered_port | default('1880')}}:1880"
        {% endif %}
            dns:
              - 172.17.0.1
#---------------------------------------------------------------------------------------------
#  - name: "enable ssl certificate resolver (if public domain)"
#    command: "sed -i 's%#- traefik.http.routers.nodered.tls.certresolver=%- traefik.http.routers.nodered.tls.certresolver=%g' compose.yml"
#    args:
#      chdir: "{{base_dir}}/compose/{{stack}}"
#    when: domain_is_public
#---------------------------------------------------------------------------------------------
  - name: "start compose stack"
    become: true
    become_method: sudo
    command: "docker compose up -d"
    args:
      chdir: "{{base_dir}}/compose/{{stack}}"
