- name: deploy Vintage Story Dedicated Server
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  vars:
    stack: "vintage-story"
    image: "sknnr/vintage-story-server:latest"
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose' directory"
    file:
      path: "{{base_dir}}/compose"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/compose/{{stack}}' directory"
    file:
      path: "{{base_dir}}/compose/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "creating '{{base_dir}}/docker/{{stack}}' directory"
    become: true
    become_method: sudo
    file:
      path: "{{base_dir}}/docker/{{stack}}"
      state: directory
      owner: "{{ssh_user}}"
#---------------------------------------------------------------------------------------------
  - name: "writing '{{base_dir}}/compose/{{stack}}/compose.yml'"
    become: true
    become_method: sudo
    copy:
      dest: "{{base_dir}}/compose/{{stack}}/compose.yml"
      owner: "{{ssh_user}}"
      content: |
        services:
          vintage-story:
            restart: unless-stopped
            container_name: vintage-story
            image: sknnr/vintage-story-server:latest
            ports:
              - "{{ vintage_story_port | default('42420') }}:42420/tcp"
              - "{{ vintage_story_port | default('42420') }}:42420/udp"
            environment:
              - GAME_VERSION=1.22.2
              - serverName={{ vintage_story_server_name | default('Vintage Story Dedicated Server') }}
              - serverDescription=A Vintage Story Server
              - port={{ vintage_story_port | default('42420') }}
              - maxPlayers={{ vintage_story_max_players | default('16') }}
              - password={{ vintage_story_password | default('changeme') }}
              - worldName=VintageWorld
              - gameMode=survival
            volumes:
              - "{{base_dir}}/docker/{{stack}}:/home/vintagestory/data"
#---------------------------------------------------------------------------------------------
  - name: "start compose stack"
    become: true
    become_method: sudo
    command: "docker compose up -d"
    args:
      chdir: "{{base_dir}}/compose/{{stack}}"
