- name: install Pidgin (Flatpak)
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "install Pidgin (im.pidgin.Pidgin) from flathub"
    become: true
    become_method: sudo
    command: "flatpak install --assumeyes --noninteractive flathub im.pidgin.Pidgin"
    register: flatpak_install
    changed_when: "'Installing' in flatpak_install.stdout"
