- name: install .NET SDK
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "ensure 'dotnet-sdk-8.0' installed (latest)"
    become: true
    become_method: sudo
    apt:
      name: dotnet-sdk-8.0
      state: latest
      update_cache: yes
