- name: install Lutris (Flatpak)
  hosts: all
  remote_user: "{{ssh_user}}"
  gather_facts: no
  tasks:
#---------------------------------------------------------------------------------------------
  - name: "install Lutris (net.lutris.Lutris) from flathub"
    become: true
    become_method: sudo
    command: "flatpak install --assumeyes --noninteractive flathub net.lutris.Lutris"
    register: flatpak_install
    changed_when: "'Installing' in flatpak_install.stdout"
